### ISSUE TITLE
git clone LBLRTM.git - unable to checkout 'cross-sections' error

### ISSUE THREAD

**Issue by gerbteam** [AER-RC/LBLRTM#14]
Hi,

I'm trying to clone the latest release of LBLRTM v12.11 following the instructions on the AER-RC/LBLRTM Github site, and I receive an error associated with the cross-sections. Please can you advise?

Many thanks,
Rich (output appended below - running on CentOS 7.9.2009)

-bash-4.2$ git clone --recursive git@github.com:AER-RC/LBLRTM.git
Cloning into 'LBLRTM'...
Enter passphrase for key '/home/bantges/.ssh/id_ed25519':
remote: Enumerating objects: 4337, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 4337 (delta 51), reused 54 (delta 27), pack-reused 4248
Receiving objects: 100% (4337/4337), 6.43 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (3100/3100), done.
Submodule 'aer_rt_utils' (https://github.com/AER-RC/aer_rt_utils.git) registered for path 'aer_rt_utils'
Submodule 'cross-sections' (https://github.com/AER-RC/cross-sections.git) registered for path 'cross-sections'
Cloning into 'aer_rt_utils'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 15 (delta 12), reused 15 (delta 12), pack-reused 0
Unpacking objects: 100% (15/15), done.
Submodule path 'aer_rt_utils': checked out '13f3a75ddd98fddcf0c4414031acd0d321be8569'
Cloning into 'cross-sections'...
remote: Enumerating objects: 542, done.
remote: Counting objects: 100% (542/542), done.
remote: Compressing objects: 100% (468/468), done.
remote: Total 542 (delta 77), reused 534 (delta 73), pack-reused 0
Receiving objects: 100% (542/542), 24.42 MiB | 20.00 MiB/s, done.
Resolving deltas: 100% (77/77), done.
fatal: reference is not a tree: dc9cfadfd002c594aea1764a61b38d7a7e525e1f
Unable to checkout 'dc9cfadfd002c594aea1764a61b38d7a7e525e1f' in submodule path 'cross-sections'
-bash-4.2$

**Comment by pernak18** [comment]
Hi Rich,

Recently, we switched from SSH key authentication to HTTPS because some users did not have an SSH key setup. We have a few options since it looks like this is no the case for you:

1. Edit your `.gitmodules` to [revert back to the SSH protocol](https://github.com/AER-RC/LBLRTM/commit/524003b598e82d8e5611f2406ab2eb1e6b2f50a4#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584)
2. [Create a personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) for usage with the HTTPS protocol (you'll use your token as your password at the command line when prompted by `git` for a user and password)

Item 1 may still not work correctly because I see your key is of type ed25519. I've only used RSA-type keys. But the [GitHub example](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases) uses ed25519 so maybe you're OK.

Please let us know what works.

Thanks!

**Comment by pernak18** [comment]
@gerbteam i'm closing for now but feel free to reopen if my recommendation did not help

please and thanks,
