### ISSUE TITLE
TAPE5 Format for LBLRRTM

### ISSUE THREAD

**Issue by mercifulforyou** [AER-RC/LBLRTM#7]
I can't understand the TAPE5 for LBLRTM ，could you please give me an accurate interpretation.
for example 
```
$ Simple TAPE5
 HI=1 F4=1 CN=1 AE=0 EM=1 SC=0 FI=0 PL=0 TS=0 AM=1 MG=0 LA=0 OD=0 XS=0   00   00
 1000.0000 1200.0000       0.0                 0.0       0.0    0.0000     0.000    0            0.0
  294.2000    1.000  
    6    2    0    0    0        
   100.000     0.000   180.000

-1.
$ Transfer to ASCII plotting data
 HI=0 F4=0 CN=0 AE=0 EM=0 SC=0 FI=0 PL=1 TS=0 AM=0 MG=0 LA=0 MS=0 XS=0    0    0
 1000.0000 1200.0000   10.2000  100.0000    5    0   12    0     1.000 0  0    0
    0.0000    1.2000    7.0200    0.2000    4    0    1    1    0    0 0    3 27
 1000.0000 1200.0000   10.2000  100.0000    5    0   12    0     1.000 0  0    0
    0.0000    1.2000    7.0200    0.2000    4    0    1    1    1    0 0    3 28
-1.
% US STD Atmosphere: Nadir viewing from 100 km down to the surface
```
there are too many terms that i can not understand it.

**Comment by pernak18** [comment]
hi @mercifulforyou apologies -- i did not get a notification that this issue was created. 

in your clone, try to open up `LBLRTM/docs/html/lblrtm_instructions_frame.html` in your browser. then focus on the following records (I've included a high-level explanation of what is being specified):

- _Record 1.2_: use a Voigt profile (`HI=1`), +/- 25 cm-1 at all altitudes (`F4=1`, contributions at a given wavenumber from lines in a 25 cm-1 window), radiance and transmittance calculations (`EM=1`), do use LBLATM to calculate molecular column amounts (`AM=1`, user must provide layer amounts if `AM=0`, which is more complicated)
- _Record 1.3_: calculate radiative transfer from 1000-1200 cm-1
- _Record 1.4_:  surface temperature of 294.2 K; only use linear term in frequency-dependent boundary emissivity, which is unity
- _Record 3.1_: required since `AM=1`; use a US Standard Atmosphere from 1976 for the profile; with a slant path from `H1` to `H2` (defined in Record 3.2)
- _Record 3.2_: observer altitude and endpoint altitudes and viewing/zenith angle (180 degree zenith angle implies downward observing from 100 km to surface, as alluded to in final line)

the `-1` tells LBLRTM it is at the end of the specifications for radiance and transmittance calculations, which show up in `ODInt` files.

i don't have as much experience with the second part (`Transfer to ASCII plotting data`), but you can look at Records 12.2A and 12.3A in the instructions. You basically are writing out two ASCII files with spectra in them -- one with upwelling radiance, the other downwelling. Plotting is not actually performed. Note this quote after record 12.3A:

>               A '-1.' within columns 1-10 will terminate plotting.

Hope that helps. @kcadyper please add anything you think needs to be said.

**Comment by mercifulforyou** [comment]
Thank you so much for answering my question.This helped me a lot.

**Comment by pernak18** [comment]
thanks for your interest in our models!
