### ISSUE TITLE
How to get SOLAR.RAD file？

### ISSUE THREAD

**Issue by WinKevin66** [AER-RC/LBLRTM#75]
Hi,
I would like to know, how can I get SLOAR.RAD file. I found it in run_examples file, but which doesn't in my band range. 
And I also saw the Q&A 8, which says 'A SOLAR.RAD file can be generated with program extract_solar available on the AER RT web site and the Kurucz solar source function', but I can't find that.It seems that there have two type of SLOAR.RAD, one is nrlssi2, another is kurucz.
Please, give me a way to get it
Thanks!

**Comment by pernak18** [comment]
@WinKevin66 please see our [SSF repo](https://github.com/AER-RC/solar-source-function). you have to build the executable and run with binaries that are publicly available. there are run example directories that contain `SOLAR_control` files that are similar to `TAPE5` files for LBL. I didn't fill in the "Run Examples" section of  `README.md` and it's been a while since i've run the code, but try staging the files in `data`, then building the executable, then creating a `SOLAR_control` in the same directory as the executable, then running.
